import fs from 'node:fs/promises';
const html = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><script src="assets/gsap.min.js"></script><style>
@font-face{font-family:Pool;src:url('assets/arial.ttf')}@font-face{font-family:Pool;src:url('assets/arial-bold.ttf');font-weight:700}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;background:#092d49;color:#fff;font-family:Pool}#root{position:relative;width:100%;height:100%;overflow:hidden}.photo{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:65% center}.shade{position:absolute;inset:0;background:linear-gradient(90deg,rgba(5,28,48,.96),rgba(5,28,48,.76) 57%,rgba(5,28,48,.14))}.brand{position:absolute;left:40px;top:34px;font-size:19px;letter-spacing:2px;font-weight:700}.city{position:absolute;left:40px;top:66px;font-size:17px;color:#c0dfff}.deadline{position:absolute;left:40px;top:108px;background:#c2e1ff;color:#092d49;border-radius:30px;padding:10px 18px;font-size:17px;font-weight:700}.headline{position:absolute;left:40px;top:190px;font-size:62px;line-height:1.05;letter-spacing:-2px;font-weight:700;width:550px}.gift{position:absolute;left:40px;top:343px;font-size:38px;color:#c2e1ff;font-weight:700}.terms{position:absolute;left:40px;top:421px;font-size:24px}.price{position:absolute;left:40px;top:469px;font-size:44px;font-weight:700}.note{position:absolute;left:40px;top:524px;font-size:18px;line-height:1.35;width:570px;color:#e1edfa}.cta{position:absolute;left:40px;top:596px;border-radius:17px;background:#c2e1ff;color:#092d49;padding:16px 26px;font-size:24px;font-weight:700}.url{position:absolute;left:40px;bottom:24px;font-size:16px;color:#d7e8f6}.second{opacity:0}.visit{font-size:76px}.subvisit{font-size:27px;letter-spacing:0}.second.gift{font-size:31px;top:352px}
</style></head><body><div id="root" data-composition-id="openpool-offer" data-width="720" data-height="720" data-duration="8" data-fps="30"><img class="photo" src="assets/pool-view.jpg"><div class="shade"></div><div class="brand">ОТКРЫТЫЙ БАССЕЙН</div><div class="city">Хабаровск · Советская, 1 к4</div><div class="deadline">Акция до 9 октября</div><div class="headline first">30 посещений<br>бассейна</div><div class="gift first">Баня в подарок</div><div class="headline second"><span class="visit">499 ₽</span><br><span class="subvisit">за визит в абонементе</span></div><div class="gift second">30 посещений + баня</div><div class="terms">90 дней · сеанс 70 минут</div><div class="price">14 970 ₽</div><div class="note">Полная стоимость абонемента.<br>499 ₽ при использовании всех 30 посещений.</div><div class="cta">Узнать условия</div><div class="url">open-pool.ru</div></div><script>
const tl=gsap.timeline({paused:true});
tl.fromTo('.photo',{scale:1},{scale:1.035,duration:8,ease:'none'},0);
tl.fromTo('.first',{opacity:1,y:0},{opacity:0,y:-14,duration:.3,ease:'power2.in'},3.4);
tl.fromTo('.second',{opacity:0,y:16},{opacity:1,y:0,duration:.4,ease:'power2.out'},3.8);
tl.fromTo('.cta',{scale:1},{scale:1.025,duration:.4,ease:'power2.inOut',yoyo:true,repeat:1},6.3);
window.__timelines={'openpool-offer':tl};
</script></body></html>`;
await fs.writeFile(new URL('index.html',import.meta.url),html);
